keyword: "afcluster"           
gap_cutoff: 0.25
random_seed: 42
outdir: "output" # output directory
tmpdir: "tmp" # temporary directory for msas
num_seeds: 4
amber_relax: False
cluster_method: "dbscan"

zip_outputs: True

dbscan:
  min_samples: 10
  eps_val: null           
  min_eps: 3
  max_eps: 20.0
  eps_step: 0.5 

path_vars:
  PATH: "/usr/local/envs/colabfold/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
  XDG_CACHE_HOME: "./cache" # path to xdg cache  
  MPLCONFIGDIR: "./cache" # path to matplotlib cache
